import { useEffect, useState } from 'react';
import type { ChangeEvent, ReactNode } from 'react';
import { AlertCircle, CheckCircle2, Eye, FileCheck2, FileSpreadsheet, Loader2, Pencil, RotateCcw, Trash2, Upload, X } from 'lucide-react';
import api from '../services/api';
import './AIChatV2Import.css';

const LANGUAGES = ['EN', 'FR', 'ES', 'DE'];
const LEVELS = ['A1', 'A2', 'B1', 'B2'];
type LevelContent = { level: string; instructions_ai: string; objective_user_verify: string; user_scenarios: Record<string, string[]> };
type Exercise = { exercise_id: string; category: string; subcategory: string; ai_role: string; user_role: string; number_of_user_turns: number; topics: Record<string, string>; titles: Record<string, string>; levels: LevelContent[] };
type Catalog = { id: number; part1_filename?: string | null; part2_filename?: string | null; exercise_count: number; level_count: number; exercises: Exercise[] };
type Rule = { level: string; language_rules: string; correction_policy: string };
type Toast = { tone: 'success' | 'error'; text: string };
type ImportBatch = { id: number; operation_type: string; part1_filename?: string | null; part2_filename?: string | null; added_count: number; updated_count: number; exercise_count: number; rolled_back_at?: string | null };
type ImportConflict = { new_exercise_count: number; updated_exercise_count: number; conflicting_exercise_ids: string[] };

const copy = (exercise: Exercise) => JSON.parse(JSON.stringify(exercise)) as Exercise;
const textFor = (values: Record<string, string>, fallback: string) => values.EN || Object.values(values).find(Boolean) || fallback;
const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;

function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  return <div className="ai-modal-backdrop" onMouseDown={onClose}><section className="ai-modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><header className="ai-modal-header"><h2>{title}</h2><button className="btn btn-secondary ai-icon-button" onClick={onClose} aria-label="Close dialog"><X size={18} /></button></header>{children}</section></div>;
}

function UploadSlot({ label, description, file, onChange }: { label: string; description: string; file: File | null; onChange: (event: ChangeEvent<HTMLInputElement>) => void }) {
  return <label className={`ai-import-slot ${file ? 'is-selected' : ''}`}><input className="ai-import-file-input" type="file" accept=".csv,text/csv" onChange={onChange} /><span className="ai-import-slot-icon">{file ? <FileCheck2 size={20} /> : <FileSpreadsheet size={20} />}</span><span className="ai-import-slot-copy"><strong>{label}</strong><small>{description}</small><span className="ai-import-slot-file"><Upload size={14} />{file ? `${file.name} · ${formatBytes(file.size)}` : 'Choose CSV file'}</span></span></label>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="ai-field"><span>{label}</span>{children}</label>; }

function ExerciseForm({ value, onChange, readOnly = false }: { value: Exercise; onChange?: (next: Exercise) => void; readOnly?: boolean }) {
  const set = (key: keyof Exercise, next: unknown) => onChange?.({ ...value, [key]: next });
  const input = (value: string | number, apply: (value: string) => void, type = 'text') => <input disabled={readOnly} type={type} value={value} onChange={(event) => apply(event.target.value)} />;
  return <div className="ai-exercise-form">
    <section className="ai-form-section"><h3>Exercise details</h3><div className="ai-field-grid"><Field label="Exercise ID">{input(value.exercise_id, () => {})}</Field><Field label="Category">{input(value.category, (next) => set('category', next))}</Field><Field label="Sub-category">{input(value.subcategory, (next) => set('subcategory', next))}</Field><Field label="AI role">{input(value.ai_role, (next) => set('ai_role', next))}</Field><Field label="Learner role">{input(value.user_role, (next) => set('user_role', next))}</Field><Field label="User turn limit">{input(value.number_of_user_turns, (next) => set('number_of_user_turns', Number(next)), 'number')}</Field></div></section>
    <section className="ai-form-section"><h3>Translated topic and scenario title</h3><div className="ai-language-grid">{LANGUAGES.map((language) => <div className="ai-language-card" key={language}><strong>{language}</strong><Field label="Topic">{input(value.topics[language] || '', (next) => set('topics', { ...value.topics, [language]: next }))}</Field><Field label="Scenario title">{input(value.titles[language] || '', (next) => set('titles', { ...value.titles, [language]: next }))}</Field></div>)}</div></section>
    {LEVELS.map((level) => { const current = value.levels.find((item) => item.level === level); if (!current) return null; const update = (next: LevelContent) => set('levels', value.levels.map((item) => item.level === level ? next : item)); return <details className="ai-level-details" key={level} open={readOnly}><summary>{level} content</summary><div className="ai-level-content"><Field label="AI instruction"><textarea disabled={readOnly} value={current.instructions_ai} onChange={(event) => update({ ...current, instructions_ai: event.target.value })} rows={5} /></Field><Field label="Feedback objective"><textarea disabled={readOnly} value={current.objective_user_verify} onChange={(event) => update({ ...current, objective_user_verify: event.target.value })} rows={4} /></Field><div className="ai-language-grid">{LANGUAGES.map((language) => <div className="ai-language-card" key={language}><strong>{language} learner scenarios</strong>{[0, 1, 2].map((index) => <textarea key={index} disabled={readOnly} value={current.user_scenarios[language]?.[index] || ''} onChange={(event) => { const scenarios = [...(current.user_scenarios[language] || ['', '', ''])]; scenarios[index] = event.target.value; update({ ...current, user_scenarios: { ...current.user_scenarios, [language]: scenarios } }); }} rows={3} placeholder={`Scenario ${index + 1}`} />)}</div>)}</div></div></details>; })}
  </div>;
}

export default function AIChatV2Import() {
  const [part1, setPart1] = useState<File | null>(null); const [part2, setPart2] = useState<File | null>(null); const [catalog, setCatalog] = useState<Catalog | null>(null); const [rules, setRules] = useState<Rule[]>([]); const [imports, setImports] = useState<ImportBatch[]>([]); const [toast, setToast] = useState<Toast | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [viewing, setViewing] = useState<Exercise | null>(null); const [editing, setEditing] = useState<Exercise | null>(null); const [pendingSave, setPendingSave] = useState<Exercise | null>(null); const [pendingDelete, setPendingDelete] = useState<Exercise | null>(null); const [importConflict, setImportConflict] = useState<ImportConflict | null>(null); const [pendingRollback, setPendingRollback] = useState<ImportBatch | null>(null); const [selectedImportId, setSelectedImportId] = useState<number | null>(null); const [importDetail, setImportDetail] = useState<{ id: number; exercise_ids: string[] } | null>(null);
  const load = async () => { const [catalogResponse, rulesResponse, importResponse] = await Promise.all([api.get<{ catalog: Catalog | null }>('/admin/ai-practice-v2/catalog'), api.get<{ rules: Rule[] }>('/admin/ai-practice-v2/universal-rules'), api.get<{ imports: ImportBatch[] }>('/admin/ai-practice-v2/imports')]); setCatalog(catalogResponse.data.catalog); setRules(rulesResponse.data.rules); setImports(importResponse.data.imports); };
  useEffect(() => { load().catch(() => setToast({ tone: 'error', text: 'Could not load AI Practice content. Check the backend and try again.' })).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!toast) return; const timeout = window.setTimeout(() => setToast(null), 4500); return () => window.clearTimeout(timeout); }, [toast]);
  const select = (setter: (file: File | null) => void) => (event: ChangeEvent<HTMLInputElement>) => setter(event.target.files?.[0] || null);
  const form = () => { const data = new FormData(); if (part1) data.append('part1', part1); if (part2) data.append('part2', part2); return data; };
  const errorText = (error: unknown) => { const detail = (error as { response?: { data?: { detail?: { errors?: string[]; message?: string } | string } } }).response?.data?.detail; return typeof detail === 'object' && detail?.errors?.length ? detail.errors.join(' ') : typeof detail === 'object' && detail?.message ? detail.message : typeof detail === 'string' ? detail : 'Please check the CSV files and try again.'; };
  const apply = async (confirmUpdates = false) => { if (!part1 || !part2) { setToast({ tone: 'error', text: 'Choose both Part 1 and Part 2 CSV files first.' }); return; } setBusy(true); setToast(null); try { const data = form(); if (confirmUpdates) data.append('confirm_updates', 'true'); const response = await api.post<{ imported_exercise_count: number; updated_exercise_count: number; exercise_count: number }>('/admin/ai-practice-v2/import', data); setPart1(null); setPart2(null); setImportConflict(null); const { imported_exercise_count, updated_exercise_count, exercise_count } = response.data; setToast({ tone: 'success', text: `Imported ${imported_exercise_count} exercise(s)${updated_exercise_count ? ` and updated ${updated_exercise_count} matching ID(s)` : ''}. ${exercise_count} exercise(s) are now live.` }); await load(); } catch (error) { const detail = (error as { response?: { status?: number; data?: { detail?: ImportConflict } } }).response?.data?.detail; if ((error as { response?: { status?: number } }).response?.status === 409 && detail?.conflicting_exercise_ids) setImportConflict(detail); else setToast({ tone: 'error', text: errorText(error) }); } finally { setBusy(false); } };
  const save = async (exercise: Exercise) => { setBusy(true); try { await api.put(`/admin/ai-practice-v2/catalog/exercises/${encodeURIComponent(exercise.exercise_id)}`, { category: exercise.category, subcategory: exercise.subcategory, ai_role: exercise.ai_role, user_role: exercise.user_role, number_of_user_turns: exercise.number_of_user_turns, topics: exercise.topics, titles: exercise.titles, levels: exercise.levels }); setPendingSave(null); setEditing(null); setToast({ tone: 'success', text: `${exercise.exercise_id} was saved and is live for new learner sessions.` }); await load(); } catch (error) { setToast({ tone: 'error', text: errorText(error) }); } finally { setBusy(false); } };
  const remove = async (exercise: Exercise) => { setBusy(true); try { await api.delete(`/admin/ai-practice-v2/catalog/exercises/${encodeURIComponent(exercise.exercise_id)}`); setPendingDelete(null); setToast({ tone: 'success', text: `${exercise.exercise_id} was removed from the live catalogue.` }); await load(); } catch (error) { setToast({ tone: 'error', text: errorText(error) }); } finally { setBusy(false); } };
  const rollback = async (item: ImportBatch) => { setBusy(true); try { await api.post(`/admin/ai-practice-v2/imports/${item.id}/rollback`); setPendingRollback(null); setToast({ tone: 'success', text: `Import #${item.id} was rolled back.` }); await load(); } catch (error) { const detail = (error as { response?: { data?: { detail?: { conflicting_exercise_ids?: string[]; message?: string } } } }).response?.data?.detail; setToast({ tone: 'error', text: detail?.conflicting_exercise_ids?.length ? `${detail.message} ${detail.conflicting_exercise_ids.join(', ')}` : errorText(error) }); } finally { setBusy(false); } };
  const viewImportDetail = async () => { if (!selectedImportId) return; setBusy(true); try { setImportDetail((await api.get<{ id: number; exercise_ids: string[] }>(`/admin/ai-practice-v2/imports/${selectedImportId}`)).data); } catch (error) { setToast({ tone: 'error', text: errorText(error) }); } finally { setBusy(false); } };
  const fileCount = Number(Boolean(part1)) + Number(Boolean(part2)); const fileSize = (part1?.size || 0) + (part2?.size || 0);
  return <main className="ai-practice-admin"><header className="ai-page-header"><div><p>Content management</p><h1>AI Practice</h1><span>Manage the live Chat catalogue without affecting active conversations.</span></div><div className="ai-header-stats"><div><strong>{catalog?.exercise_count ?? 0}</strong><span>live exercises</span></div><div><strong>{catalog?.level_count ?? 0}</strong><span>level entries</span></div></div></header>
    <section className="ai-panel"><div className="ai-section-heading"><div><h2>Import exercises</h2><p>New IDs import immediately; matching IDs require your confirmation.</p></div><span className="ai-limit-note">25 MB per file maximum</span></div><div className="ai-upload-grid"><UploadSlot label="Part 1 · Exercise catalogue" description="Roles, topics, titles and turn limits." file={part1} onChange={select(setPart1)} /><UploadSlot label="Part 2 · Level content" description="AI instructions, objectives and scenarios." file={part2} onChange={select(setPart2)} /></div><div className="ai-import-footer"><span>{fileCount}/2 files selected{fileCount ? ` · ${formatBytes(fileSize)} total` : ''}</span><button className="btn btn-primary" disabled={busy || !part1 || !part2} onClick={() => apply()}>{busy ? <Loader2 size={17} className="animate-spin" /> : <Upload size={17} />}{busy ? 'Importing…' : 'Import exercises'}</button></div></section>
    <section className="ai-panel"><div className="ai-section-heading"><div><h2>Current conversations</h2><p>{catalog ? [catalog.part1_filename, catalog.part2_filename].filter(Boolean).join(' · ') || 'Current live catalogue' : 'No CSV catalogue is currently live.'}</p></div><span className="ai-status-dot"><i />Live catalogue</span></div>{loading ? <div className="ai-empty-state">Loading conversations…</div> : catalog?.exercises.length ? <><div className="ai-conversation-table-wrap"><table className="ai-conversation-table"><thead><tr><th>ID</th><th>Conversation</th><th>Roles</th><th>Turns</th><th>Levels</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{catalog.exercises.map((item) => <tr key={item.exercise_id}><td><strong>{item.exercise_id}</strong></td><td><strong>{textFor(item.topics, 'Untitled conversation')}</strong><small>{textFor(item.titles, 'No scenario title')}</small></td><td>{item.ai_role}<small>Learner: {item.user_role}</small></td><td><span className="ai-turn-badge">{item.number_of_user_turns}</span></td><td><div className="ai-level-pills">{item.levels.map((level) => <span key={level.level}>{level.level}</span>)}</div></td><td><div className="ai-row-actions"><button className="btn btn-secondary ai-icon-button" aria-label={`View ${item.exercise_id}`} onClick={() => setViewing(item)}><Eye size={16} /></button><button className="btn btn-secondary ai-icon-button" aria-label={`Edit ${item.exercise_id}`} onClick={() => setEditing(copy(item))}><Pencil size={16} /></button><button className="btn btn-secondary ai-icon-button ai-delete-button" aria-label={`Delete ${item.exercise_id}`} disabled={busy} onClick={() => setPendingDelete(item)}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div><div className="ai-conversation-cards">{catalog.exercises.map((item) => <article className="ai-conversation-card" key={item.exercise_id}><div className="ai-card-topline"><strong>{item.exercise_id}</strong><span className="ai-turn-badge">{item.number_of_user_turns} turns</span></div><h3>{textFor(item.topics, 'Untitled conversation')}</h3><p>{textFor(item.titles, 'No scenario title')}</p><span>{item.ai_role} · learner: {item.user_role}</span><div className="ai-level-pills">{item.levels.map((level) => <span key={level.level}>{level.level}</span>)}</div><div className="ai-card-actions"><button className="btn btn-secondary" onClick={() => setViewing(item)}><Eye size={16} />View</button><button className="btn btn-secondary" onClick={() => setEditing(copy(item))}><Pencil size={16} />Edit</button><button className="btn btn-secondary ai-delete-button" disabled={busy} onClick={() => setPendingDelete(item)}><Trash2 size={16} />Delete</button></div></article>)}</div></> : <div className="ai-empty-state">Upload Part 1 and Part 2 CSV files to add conversations.</div>}</section>
    <section className="ai-panel"><div className="ai-section-heading"><div><h2>Universal CEFR rules</h2><p>Read-only language and correction rules used in every conversation.</p></div></div><div className="ai-rules-grid">{rules.map((rule) => <article key={rule.level}><strong>{rule.level}</strong><p>{rule.language_rules}</p><small><b>Correction:</b> {rule.correction_policy}</small></article>)}</div></section>
    <section className="ai-panel"><div className="ai-section-heading"><div><h2>Import history</h2><p>Rollback is available only when newer changes have not touched the same exercise.</p></div></div>{imports.length ? <div className="ai-history-list">{imports.map((item) => <article className="ai-history-item" key={item.id}><div><strong>#{item.id} · {item.operation_type.replace('_', ' ')}</strong><p>{item.operation_type === 'csv_import' ? `${item.part1_filename} + ${item.part2_filename}` : 'Manual change'} · {item.added_count} added · {item.updated_count} updated</p><small>{item.exercise_count} exercise(s) · select below to view IDs</small></div>{item.operation_type === 'csv_import' && !item.rolled_back_at && <button className="btn btn-secondary" disabled={busy} onClick={() => setPendingRollback(item)}><RotateCcw size={16} />Rollback</button>}{item.rolled_back_at && <span className="ai-muted">Rolled back</span>}</article>)}</div> : <div className="ai-empty-state">No imports yet.</div>}{imports.length > 0 && <div className="ai-history-controls"><select aria-label="Import to inspect" value={selectedImportId || ''} onChange={(event) => setSelectedImportId(Number(event.target.value) || null)}><option value="">Select an import to inspect</option>{imports.map((item) => <option key={item.id} value={item.id}>Import #{item.id} · {item.exercise_count} exercise(s)</option>)}</select><button className="btn btn-secondary" disabled={busy || !selectedImportId} onClick={viewImportDetail}>View exercise IDs</button></div>}</section>
    {importDetail && <Modal title={`Import #${importDetail.id} exercise IDs`} onClose={() => setImportDetail(null)}><p className="ai-modal-copy">{importDetail.exercise_ids.length} exercise(s) in this import.</p><div className="ai-id-list">{importDetail.exercise_ids.map((id) => <div key={id}>{id}</div>)}</div><div className="ai-modal-actions"><button className="btn btn-primary" onClick={() => setImportDetail(null)}>Close</button></div></Modal>}
    {importConflict && <Modal title="Matching Exercise IDs found" onClose={() => !busy && setImportConflict(null)}><p className="ai-modal-copy">This upload adds {importConflict.new_exercise_count} new exercise(s) and updates {importConflict.updated_exercise_count} existing exercise(s). The following content will be replaced for new learner sessions:</p><div className="ai-id-list">{importConflict.conflicting_exercise_ids.map((id) => <div key={id}>{id}</div>)}</div><div className="ai-modal-actions"><button className="btn btn-secondary" disabled={busy} onClick={() => setImportConflict(null)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={() => apply(true)}><Upload size={17} />Apply changes</button></div></Modal>}
    {pendingRollback && <Modal title="Rollback CSV import?" onClose={() => !busy && setPendingRollback(null)}><p className="ai-modal-copy">Rollback import <strong>#{pendingRollback.id}</strong>? It restores its previous exercise versions unless a later change conflicts.</p><div className="ai-modal-actions"><button className="btn btn-secondary" disabled={busy} onClick={() => setPendingRollback(null)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={() => rollback(pendingRollback)}><RotateCcw size={17} />Rollback import</button></div></Modal>}
    {viewing && <Modal title={`View ${viewing.exercise_id}`} onClose={() => setViewing(null)}><ExerciseForm value={viewing} readOnly /><div className="ai-modal-actions"><button className="btn btn-primary" onClick={() => setViewing(null)}>Close</button></div></Modal>}
    {editing && <Modal title={`Edit ${editing.exercise_id}`} onClose={() => !busy && setEditing(null)}><ExerciseForm value={editing} onChange={setEditing} /><div className="ai-modal-actions"><button className="btn btn-secondary" disabled={busy} onClick={() => setEditing(null)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={() => setPendingSave(copy(editing))}><CheckCircle2 size={17} />Save changes</button></div></Modal>}
    {pendingSave && <Modal title="Save changes?" onClose={() => !busy && setPendingSave(null)}><p className="ai-modal-copy">Save the changes to <strong>{pendingSave.exercise_id}</strong>? They will be live for new learner sessions. Conversations already in progress are not affected.</p><div className="ai-modal-actions"><button className="btn btn-secondary" disabled={busy} onClick={() => setPendingSave(null)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={() => save(pendingSave)}><CheckCircle2 size={17} />Save changes</button></div></Modal>}
    {pendingDelete && <Modal title="Delete conversation?" onClose={() => !busy && setPendingDelete(null)}><p className="ai-modal-copy">Delete <strong>{pendingDelete.exercise_id}</strong> from the live catalogue? It will no longer be available to new learners. Conversations already in progress are not affected.</p><div className="ai-modal-actions"><button className="btn btn-secondary" disabled={busy} onClick={() => setPendingDelete(null)}>Cancel</button><button className="btn btn-primary ai-danger-button" disabled={busy} onClick={() => remove(pendingDelete)}><Trash2 size={17} />Delete conversation</button></div></Modal>}
    {toast && <div role={toast.tone === 'error' ? 'alert' : 'status'} className={`ai-toast ${toast.tone}`}>{toast.tone === 'success' ? <CheckCircle2 size={19} /> : <AlertCircle size={19} />}<p>{toast.text}</p><button className="btn btn-secondary ai-icon-button" onClick={() => setToast(null)} aria-label="Dismiss notification"><X size={16} /></button></div>}
  </main>;
}
